function prm = getPrm(ind)
    prm.filterWidth = 2;
    prm.doMinContrastTest = true;
    prm.minContrast = 8;
    prm.minLength = 5;
    prm.nmsThres = 0.5;
    prm.eliminateEpsilons = true;
    prm.eliminateEpsilonsFactor = 0.225;
    prm.varTestAlpha = 0.1;
    prm.eliminateShortEdges = true;
    prm.nmsWindow = 3;
    prm.highestTurnAngle = 48;
    prm.radian = true;
    prm.shapeScoreWeight = 0.001;%0.0542;%0.001;
    prm.radianScoreWeight = 0.0545;
    prm.sigmaShape = 30;
    prm.addShift = true;
    prm.normalizeScore = false;
    prm.newThreshold = false;
    prm.newSearchSpace = false;
    prm.searchSpaceFact = 7;
    prm.doVarTest = true;
    prm.maxParam = 0;
    prm.jLevel = 3;
    prm.tFact = 1;
    prm.block = 129;
    prm.gap = 10;
    prm.padWithNan = false;
    prm.sigma = 0.1;
    prm.doNMS = true;
    prm.expConst = 0;
end

